version: "3"
services:
  yourapp: 
    ports:
      - '8080:8080'
    build:
      context: ./APP
      dockerfile: Dockerfile
  yourwebserver:
    build:
      context: ./WEBSERVER
      dockerfile: Dockerfile
  yourdb:
    restart: 'always'
    build:
      context: ./DB
      dockerfile: Dockerfile
    ports:
      - '5432:5432'
    env_file: DB/.env
    networks:
      localdev:
        aliases:
          - 'postgres'

networks:
  localdev:


